use crate::engine::Engine;
use crate::model::{
    GeneratedLineage, GeneratedLineageBasis, GeneratedLineageStatus, GeneratedSourceOfTruthKind,
    InvestigationAnchor, RouteSegment, RouteSegmentKind,
};

use super::common::read_source;

pub(super) fn infer_generated_lineage(
    engine: &Engine,
    entry_anchor: &InvestigationAnchor,
    route: &[RouteSegment],
) -> Option<GeneratedLineage> {
    let lowered_path = entry_anchor.path.replace('\\', "/").to_ascii_lowercase();
    let explicit_path_marker = has_generated_path_marker(&lowered_path);
    let content = read_source(&engine.project_root, &entry_anchor.path).ok();
    let explicit_content_marker = content
        .as_deref()
        .is_some_and(has_generated_content_marker);
    let looks_like_client = lowered_path.contains("client")
        || lowered_path.contains("/lib/api/")
        || lowered_path.contains("/generated/")
        || lowered_path.contains("/gen/");

    if !explicit_path_marker && !explicit_content_marker && !looks_like_client {
        return None;
    }

    let source_of_truth = route
        .iter()
        .filter(|segment| segment.path != entry_anchor.path)
        .filter_map(source_of_truth_candidate)
        .max_by(|left, right| left.0.total_cmp(&right.0));

    let (status, detection_basis, confidence) = match (
        explicit_path_marker,
        explicit_content_marker,
        source_of_truth.is_some(),
    ) {
        (true, _, true) => (
            GeneratedLineageStatus::Generated,
            GeneratedLineageBasis::PathConvention,
            0.92,
        ),
        (false, true, true) => (
            GeneratedLineageStatus::Generated,
            GeneratedLineageBasis::FileBanner,
            0.88,
        ),
        (true, _, false) | (false, true, false) => (
            GeneratedLineageStatus::GeneratedUnknownSource,
            if explicit_path_marker {
                GeneratedLineageBasis::PathConvention
            } else {
                GeneratedLineageBasis::FileBanner
            },
            0.74,
        ),
        (false, false, true) => (
            GeneratedLineageStatus::SuspectedGenerated,
            GeneratedLineageBasis::AdjacentContract,
            0.61,
        ),
        _ => (
            GeneratedLineageStatus::SuspectedGenerated,
            GeneratedLineageBasis::Ambiguous,
            0.5,
        ),
    };

    Some(GeneratedLineage {
        status,
        detection_basis,
        source_of_truth_path: source_of_truth.as_ref().map(|(_, path, _)| path.clone()),
        source_of_truth_kind: source_of_truth.map(|(_, _, kind)| kind),
        confidence,
    })
}

fn has_generated_path_marker(path: &str) -> bool {
    path.contains("/generated/")
        || path.contains("/gen/")
        || path.contains(".generated.")
        || path.contains(".gen.")
        || path.ends_with("_generated.ts")
        || path.ends_with("_generated.js")
        || path.ends_with(".generated.ts")
        || path.ends_with(".generated.js")
}

fn has_generated_content_marker(content: &str) -> bool {
    let lowered = content
        .lines()
        .take(16)
        .collect::<Vec<_>>()
        .join("\n")
        .to_ascii_lowercase();
    lowered.contains("generated file")
        || lowered.contains("auto-generated")
        || lowered.contains("autogenerated")
        || lowered.contains("do not edit")
        || lowered.contains("generated by")
}

fn source_of_truth_candidate(
    segment: &RouteSegment,
) -> Option<(f32, String, GeneratedSourceOfTruthKind)> {
    let kind_score = match segment.kind {
        RouteSegmentKind::Endpoint => 0.95,
        RouteSegmentKind::Service => 0.85,
        RouteSegmentKind::Query | RouteSegmentKind::Crud => 0.8,
        RouteSegmentKind::Migration => 0.75,
        _ => return None,
    };
    let source_kind = match segment.kind {
        RouteSegmentKind::Query | RouteSegmentKind::Crud | RouteSegmentKind::Migration => {
            GeneratedSourceOfTruthKind::Schema
        }
        RouteSegmentKind::Endpoint | RouteSegmentKind::Service => {
            GeneratedSourceOfTruthKind::UpstreamContract
        }
        _ => GeneratedSourceOfTruthKind::Unknown,
    };
    Some((kind_score + segment.score * 0.05, segment.path.clone(), source_kind))
}
